export default [
    { html: 'לציין את שם החודש בקובץ שנשלח למורות', status: 'בוצע', statusColor: 'success' },
    { html: 'לסמן בצורה מודגשת במייל תגובה לקבצים את הקבצים שנכשלו', status: 'נדרשת חשיבה נוספת', statusColor: 'primary' },
    { html: 'לשלוח הודעה טלפונית למורות שטרם דיווחו', status: 'מורכב, ייתכן ויתבצע בעתיד', statusColor: 'error' },
    { html: 'אפשרות לייצא את רשימת הקבצים שהתקבלו', status: 'בוצע', statusColor: 'success' },
    { html: 'הוספת אפשרות לדיווח בזמן השיעור', status: 'בוצע', statusColor: 'success' },
    { html: 'הוספת אפשרויות בעת ייצוא תעודה לתלמידה', status: 'בוצע', statusColor: 'success' },
    { html: 'הוספת עמודת חיסורים לא מאושרים לדוח נוכחות', status: 'בוצע', statusColor: 'success' },
    { html: 'הוספת כיתת בסיס בדוח אחוזים לתלמידה', status: 'בוצע', statusColor: 'success' },
    { html: 'הוספת שדה תאריך עברי לטבלת נוכחות', status: 'בוצע', statusColor: 'success' },
    { html: 'הוספת חיסורים מאושרים לדוח אחוזים לתלמידה', status: 'בוצע', statusColor: 'success' },
    { html: 'סידור לוגו תחתון בתעודה', status: 'בוצע', statusColor: 'success' },
    { html: 'הוספת טופס ציונים', status: 'בוצע', statusColor: 'success' },
    { html: 'הוספת שיוך כיתה לטבלת נוכחות', status: 'בוצע', statusColor: 'success' },

    // { html: 'הגדרת תקופת זמן לפי תאריכים', status: 'בקרוב', statusColor: 'warning' },
    // { html: 'הגדרת תקופת זמן לפי יום בשבוע', status: 'בוצע', statusColor: 'success' },
    // { html: 'הגדרת תקופת זמן לפי יום בשנה', status: 'נדרשת חשיבה נוספת', statusColor: 'primary' },
    // { html: 'יצירת דוחות נוכחות לפי תקופת זמן', status: 'לא יבוצע', statusColor: 'error' },
].reverse();