version: "3"
services:
    frontend:
        restart: unless-stopped
        depends_on:
            - backend
        build:
            context: ./client
        environment:
            REACT_APP_API_URL: "${BACKEND_URL}:${BACKEND_PORT}"
        ports:
            - "${FRONTEND_PORT}:3000"
        volumes:
            - ./client:/app
            - /app/node_modules
            - /app/dist

    backend:
        restart: unless-stopped
        build:
            context: ./server
        environment:
            MYSQL_HOST: $MYSQL_HOST
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            JWT_SECRET: $JWT_SECRET
        depends_on:
            - mysql
        ports:
            - "${BACKEND_PORT}:3000"
        volumes: 
            - ./server:/app
            - /app/node_modules
            - /app/dist

    mysql:
        restart: unless-stopped
        build:
            context: ./db
        cap_add:
            - SYS_NICE
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        volumes:
            - "db_data:/var/lib/mysql"

    phpmyadmin:
        restart: unless-stopped
        depends_on:
            - mysql
        image: phpmyadmin
        ports:
            - "8090:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD


volumes:
    db_data:
