name: Docker Image CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage-server'
        uses: docker/build-push-action@v4
        with:
          push: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: latest,${{github.sha}}
          file: server/Dockerfile
