name: Docker Image CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: 'Build:dockerimage-client'
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: |
            ${{ github.repository_owner }}/${{ github.event.repository.name }}-client:latest
            ${{ github.repository_owner }}/${{ github.event.repository.name }}-client:${{github.sha}}

      - name: 'Build:dockerimage-server'
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: |
            ${{ github.repository_owner }}/${{ github.event.repository.name }}-server:latest
            ${{ github.repository_owner }}/${{ github.event.repository.name }}-server:${{github.sha}}
