name: Run tests on pull request

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: buzz-code/multi-repo-codespace/.github/workflows/reusable-tests.yml@2fd248e058518a8d28f0ee90f03c73e187904c7e
    with:
      run_client: true
      run_server: true

