name: Run tests on pull request

on:
  pull_request:
    branches:
      - main

jobs:
  server-tests:
    name: Run server tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: server/yarn.lock
      - run: yarn
      - run: yarn test
      - run: yarn test:e2e

  client-tests:
    name: Run client tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock
      - run: yarn
      - run: yarn test

