name: Run tests on pull request

on:
  pull_request:
    branches:
    - master

jobs:
  prepare:
    name: Prepare changes
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.changes.outputs.client }}
      server: ${{ steps.changes.outputs.server }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Filter changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          client:
            - 'client/**'
          server:
            - 'server/**'


  server-tests:
    name: Run server tests
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.server == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn
      - run: yarn test
      